export const Bibliography = [
  "Pausanias. Graeciae descriptio, 2 Vols. Biblioteca Scriptorum Graecorum et Romanorum Teubneriana. Leipzig: Teubner, 1977.",
  "Alcock, Susan E., John Cherry, and Jaś Elsner. Pausanius: Travel and Memory in Roman Greece. Oxford: Oxford University Press, 2001.",
  "Habicht, Christian. Pausanias’ Guide to Ancient Greece, 2nd ed. Sather Classical Lectures, 50. Berkeley: University of California Press, 1998.",
  "Hutton, William. Describing Greece: Landscape and Literature in the Periegesis of Pausanius. Greek Culture in a Roman World. Cambridge: Cambridge University Press, 2005.",
  "Pirenne-Delforge, Vinciane. Retour à la source: Pausanias et la religion grecque. Kernos Supplément 20. Liège: Centre international d’étude de la religion grecque antique, 2008.",
  "Pretzler, M. Pausanias: Travel Writing in Ancient Greece. Classical Literature and Society. London: Duckworth, 2007.",
  "Pritchett, William Kendrick. Pausanias Periegetes. Archaic Ellas 6. Amsterdam: Gieben, 1998.",
  "Stewart, Daniel R. “‘Most Worth Remembering’: Pausanias, Analogy, and Classical Archaeology.” Hesperia 82, no. 2 (June 1, 2013): 231–261.",
  "Plutarch. Vitae Parallelae, 2 vols., edited by Claes Lindskog and Konrat Ziegler. Biblioteca Scriptorum Graecorum et Romanorum Teubneriana. Leipzig: Teubner, 1977.",
  "Asirvatham, Sulochana Ruth. \"Classicism and Romanitas in Plutarch's De Alexandri Fortuna Aut Virtute.\" American Journal of Philology 126, no. 1 (2005): 107-25.",
  "Follet, S. \"Flavius Euphanès d'Athènes, ami de Plutarque.\" In Mélanges de linguistique et de philologie grecques offerts à Pierre Chantraine, Etudes et Commentaires 79, 35-50. Paris: Klinksiech, 1972.",
  "Follet, Simone. “Un Ami de Plutarque, L’orateur Athénien Glaukias.” In Ὀπωρα La Belle Saison de L’hellénisme, edited by Alain Billault, 85–96. Paris: University of Paris-Sarbonne, 2001.",
  "Lamberton, R. “Plutarch and the Romanization of Athens.” In The Romanization of Athens: Proceedings of an International Conference Held at Lincoln, Nebraska (April 1996), edited by Michael C. Hoff and Susan I. Rotroff, 151–60. Oxbow Monographs 94. Oxford: Oxbow, 1997.",
  "Swain, S. C. R. “Hellenic Culture and the Roman Heroes of Plutarch.” The Journal of Hellenic Studies 110 (January 1, 1990): 126–145.",
  "Philostratus. Flavii Philostrati Opera. Edited by Carl Ludwig Kayser. Biblioteca Scriptorum Graecorum et Romanorum Teubneriana. Leipzig: Teubner, 1871.",
  "Philostratus and Eunapius, The Lives of the Sophists. Translated by Wright, Wilmer C. Loeb Classical Library 134. Cambridge, MA: Harvard University Press, 1968.",
  "Philostratus. Vite dei sofisti. Translated by Maurizio Civiletti. Milan: Bompiani, 2002.",
  "Philostratus. Apollonius of Tyana. Translated by Christopher P. Jones. 3 Vols. Loeb Classical Library 458. Cambridge, MA: Harvard University Press, 2005-6.",
  "Alciphron, Aelian, and Philostratus. The Letters. Translated by A.R. Benner, F.H. Fobes. Loeb Classical Library 383. Cambridge, MA: Harvard University Press, 1949.",
  "Anderson, Graham. Philostratus, Biography and Belles Lettres in the Third Century A.D. London\u202f; Dover, N.H: Croom Helm, 1986.",
  "Avotins, Ivar and Miriam-Milner Avotins. An Index to the Lives of the Sophists. Hildesheim: Olms, 1978.",
  "Barnes, Timothy D. “Philostratos and Gordian.” Latomus 27 (1968): 581–97.",
  "Bowie, Ewen, and Jaś Elsner. Philostratus. Greek Culture in the Roman World. Cambridge, UK\u202f; New York: Cambridge University Press, 2009.",
  "Côté, Dominique. “La figure d’Eschine dans les Vies des sophistes de Philostrate.” Cahiers des études anciennes 42 (2005): 389–420.",
  "Côté, Dominique. “Les Deux Sophistiques de Philostrate).” Rhetorica: A Journal of the History of Rhetoric 24, no. 1 (February 1, 2006): 1–35.",
  "Eshleman, Kendra. “Defining the Circle of Sophists: Philostratus and the Construction of the Second Sophistic.” Classical Philology 103, no. 4 (October 1, 2008): 395–413.",
  "Penella, Robert J. \"Philostratus' Letter to Julia Domna.\" Hermes 107, no. 2 (1979).",
  "Stefec, R. “Zur Überlieferung und Textkritik der Sophistenviten Philostrats.” Wiener Studien 123 (2010): 63–93.",
  "Aulus Gellius. Noctes Atticae. Edited by P.K. Marshall. 2 vols. Oxford Classical Texts. Oxford: Oxford University Press, 1968.",
  "Aelius Aristides. P. Aelii Aristidis Opera Quae Exstant Omnia. Edited by Friedrich Walther Lenz and Charles Allison Behr. Leiden: Brill, 1976.",
  "Bosworth, A. B. A Historical Commentary on Arrian’s History of Alexander. Oxford: Clarendon Press, 1980.",
  "Boulanger, André. Aelius Aristide et la sophistique dans la province d’Asie au IIe siècle de notre ère. Bibliothèque des Écoles “Françaises d”Athènes et de Rome 126. Paris: E. de Boccard, 1923.",
  "Bucher, Gregory S. “The Origins, Program, and Composition of Appian’s Roman History.” Transactions of the American Philological Association 130 (January 1, 2000): 411–458.",
  "Oliver, James H. “The Ruling Power; a Study of the Roman Empire in the Second Century after Christ through the Roman Oration of Aelius Aristides.” Transactions of the American Philosophical Society 43, no. 4 (1953): 871–1003.",
  "Oliver, James H. “The Civilizing Power: A Study of the Panathenaic Discourse of Aelius Aristides against the Background of Literature and Cultural Conflict, with Text, Translation, and Commentary.” Transactions of the American Philosophical Society 58, no. 1 (January 1, 1968): 1–223.",
  "Bardani, Voula, and Stephen Tracy. “A New List of Athenian Ephebes and a New Archon of Athens.” Zeitschrift Für Papyrologie und Epigraphik 163 (January 1, 2007): 75–80.",
  "Dow, Sterling. “The List of Archontes, I.G.2 II 1706.” Hesperia 2, no. 3 (January 1, 1933): 418–446.",
  "Dow, Sterling. “New Readings in the Archon Lists I. G. ii2, 1713 and 1716.” American Journal of Archaeology 37, no. 4 (October 1, 1933): 578–588.",
  "Dow, Sterling. “The Lists of Athenian Archontes.” Hesperia 3, no. 2 (January 1, 1934): 140–190.",
  "Dow, Sterling. “Archons of the Period after Sulla.” Hesperia Supplements 8 (January 1, 1949): 116–451.",
  "Follet, Simone. Athènes au IIe et au IIIe siècle: études chronologiques et prosopographiques. Paris: Les Belles Lettres, 1976.",
  "Follet, Simone. “La datation de l’Archonte Dionysios (IG II2, 3968)\u202f: ses conséquences archéologiques, littéraires et épigraphiques.” Revue des Études Grecques 90, no. 428 (1977): 47–54. doi:10.3406/reg.1977.4128.",
  "Follet, Simone. “Contribution à la chronologie attique du premier siècle de notre ère.” In The Greek Renaissance in the Roman Empire\u202f: Papers from the Tenth British Museum Classical Colloquium, edited by Averil Cameron and Susan Walker, 37–44. Bulletin Supplement. London: University of London, Institute of Classical Studies, 1989.",
  "Follet, Simone. “Les deux archontes Pamménès du Ier siècle a.C. à Athènes.” Revue des Études Grecques 113, no. 1 (2000): 188–192.",
  "Graindor, Paul. Chronologie Des Archontes Athéniens Sous L’empire,. M. Lamertin: Brussels, 1922.",
  "Kapteanopoulos, Elias. \"The Archons Flavius Harpalianos and Arrius Epaphrodeitos.\" Horos 8-9 (1991): 87-91.",
  "Kanpetanopoulos, Elias. \"The Archon Phileinos.\" Epigaphica 52 (1990): 21-32.",
  "Kapetanopoulos, Elias. \"Polydeukion and the Archon Dionysios.\" Horos 7 (1989): 35-40.",
  "Kapetanopoulos, Elias. Εἰς κατάλογον Ἀθηναίων Ἀρχόντων.\" Horos 6 (1988): 21-31.",
  "Kapetanopoulos, Elias. \"Athenian Archons of A.D. 170/1-179/80.\" Rivista di filologia e di istruzione classica 112 (1984): 177-91.",
  "Kapetanopoulos, Elias. \"The Archon Memmius [Peisan]dros Kol[lyteu]s.\" Prometheus 10 (1984): 139-40.",
  "Kapetanopoulos, Elias. \"Three Athenian Archons.\" Hellenica 29 (1976): 248-66.",
  "Kapetanopoulos, Elias. \" Οἱ ἄρχοντες Γἀϊος καὶ Λούκιος.\" Ἀρχαιολογικὰ Ἀνάλεκτα ἐξ Ἀθηνῶν 6 (1973): 137-8.",
  "Kapetanopoulos, Elias. \"The Archon Q. Vibius Crispus Marathonius.\" Ἀρχαιολογικὰ Ἀνάλεκτα ἐξ Ἀθηνῶν 6 (1973): 137-8.",
  "Kolbe, W. \"Studien zur attischen Chronologie der Kaiserzeit.\" Mitteilungen des Deutschen Archäologischen Instituts 46 (1921): 105-56.",
  "Notopoulos, James A. “Studies in the Chronology of Athens under the Empire.” Hesperia 18, no. 1 (January 1, 1949): 1–57.",
  "Rotroff, Susan I. “An Athenian Archon List of the Late Second Century after Christ.” Hesperia 44, no. 4 (October 1, 1975): 402–408.",
  "Schmalz, Geoffrey C.R. Augustan and Julio-Claudian Athens: A New Epigraphy and Prosopography. Mnemosyne Supplements. Leiden: Brill, 2009.",
  "Tracy, Stephen. Attic Letter-Cutters of 229 to 86 B.C. Berkeley: University of California Press, 1990.",
  "Tracy, Stephen. The Lettering of an Athenian Mason. Hesperia Supplements 15. Princeton: American School of Classical Studies at Athens, 1975.",
  "Aleshire, Sara B. Asklepios at Athens: Epigraphic and Prosopographic Essays on the Athenian Healing Cults. Amsterdam: J.C. Gieben, 1991.",
  "Broughton, T. Robert S. The Magistrates of the Roman Republic. New York: The American Philological Association, 1951.",
  "Byrne, Sean G. Roman Citizens of Athens. Studia Hellenistica 40. Leuven: Peeters, 2003.",
  "Groag, E. and A. Stein, eds. Prosopographia Imperii Romani saec. I. II. III. 2nd edition. Berlin, 1933.",
  "Kapetanopoulos, Elias. \"The Early Expansion of Roman Citizenship into Attica during the First Part of the Empire.\" PhD diss., Yale University, 1963.",
  "Kirchner, J. Prosopographia Attica, 2 vols. Berlin, 1901-1903.",
  "Osborne, M.J. and S.B. Byrne, eds. The Foreign Residents of Attica: An Annex to the Lexicon of Greek Personal Names: Attica. Studia Hellenistica 33. Leuven, Belgium: Peeters, 1996.",
  "Osborne, M.J. and S. B. Byrne, eds. Lexicon of Greek Personal Names, vol. II, Attica. Oxford: Oxford University Press, 1994.",
  "Toepffer, Johannes. Attische Genealogie. Berlin: Weidmannsche Buchhandlung, 1889.",
  "Traill, John S. Persons of Ancient Athens, 21 vols. Toronto: Athenians, 1994.",
  "Woloch, Michael. Roman Citizenship and the Athenian Elite A.D. 96-161: Two Prosopographical Catalogues. Amsterdan: Adolf M. Hakkert, 1989.",
  "The Athenian Agora: Results of the Excavations Conducted by the American School at Athens, 35 vols. Princeton: American School of Classical Studies at Athens., 1953-2013.",
  "Aupert, Pierre, Théophile Homolle, and Jean-Pierre Michaud. Fouilles de Delphes, Vol. 3, Fasc. 2. École Français d'Athènes. Paris: De Boccard, 1909-13.",
  "Cagnat, R. Inscriptiones Graecae ad res romanas pertinentes, Reprint. Chicago: Ares Publishing, 1975.",
  "Chaniotis, A., T. Corsten, R.S. Stroud, and R.A. Tybout, eds. Supplementum Epigraphicum Graecum. Leiden: Brill, 1923-2013.",
  "Clinton, Kevin, ed. (2005). Eleusis. The Inscriptions on Stone: Documents of the Sanctuary of the Two Goddesses and Public Documents of the Deme, 3 Vols. The Archaeological Society at Athens Library 236. Athens: The Archaeological Society at Athens, 2005.",
  "Clinton, Kevin. \"Inscriptions from Eleusis.\" Archaiologike Ephemeris (1971): 81-136.",
  "Dittenberger, W., ed.. Orientis Graeci Inscriptiones Selectae. Leipzig: S. Hirzel, 1903.",
  "Dittenberger, W., ed.. Sylloge Inscriptionum Graecarum, 3rd ed. Leipzig: S. Hirzel, 1915-24.",
  "Dittenberger, W., ed. Inscriptiones Graecae, III, Inscriptiones Atticae Aetatis Romanae. Berlin, 1878-1882.",
  "Dow, S. Prytaneis. A Study of the Inscriptions Honoring the Athenian Councillors. Hesperia Supplements 1. Princeton: American School of Classical Studies at Athens, 1937.",
  "Dürrbach, Félix, Pierre Roussel, Marcel Launey, André Plassart, and Jacques Coupry. Inscriptions de Délos. Académie des inscriptions et belles lettres. Paris: Champion, 1926.",
  "Hiller von Gaetringen, F., ed. Inscriptiones Graecae, I2, editio minor, Inscriptiones Attica Euclidis anno anteriores. Berlin, 1924.",
  "Kirchhoff, A., eds. Inscriptiones Graecae, I, Inscriptiones Atticae Euclidis anno vetustiores. Berlin, 1873-91.",
  "Kirchner, J., ed. Inscriptiones Graecae, II-III, Inscriptiones Atticae Euclidis anno posteriores. Berlin, 1913-40.",
  "Kirchner, J., ed. Imagines Inscriptionum Atticarum, 2nd edition. Berlin, 1948.",
  "Koehler, U., ed. Inscriptiones Graecae, II, Inscriptiones Atticae aetatis quae est inter Euclidis annum et Augusti tempora. Berlin, 1877-1893.",
  "Miller, M. Supplementum Inscriptionum Atticarum VI: The Latin Inscriptions of Athens and Attica. Chicago: Ares, 1992.",
  "Wilson, Paul René. A Corpus of Ephebic Inscriptions from Roman Athens: 31 B.C. - 267 A.D. Melbourne: Monash University 1992.",
  "Alcock, Susan. Graecia Capta: The Landscapes of Roman Greece. Cambridge: Cambridge University Press, 1993.",
  "Alcock, Susan. “The Problem with Romanization.” In The Romanization of Athens: Proceedings of an International Conference held at Lincoln, Nebraska (April 1996), Oxbow Monographs 94, edited by Michael C. Hoff and Susan I. Rotroff, 161-82. Oxford: Oxbow, 1997",
  "Bentz, Matin and Norbert Eschbach. Panathenaika: Symposion zu den Panathenaischen Preisamphoren, Rauischholzhausen 25.11.-29.11.1998. Mainz: Philipp von Zabern, 2001.",
  "Bowersock, G.W. “Augustus on Aigina.” The Classical Quarterly, no. 14 (1964): 120-1.",
  "De Giorgi, Andrea U. \"The Greek East.\" American Journal of Archaeology 115, no. 3 (July 2011): 489-493.Ma, John. Antiochus III and the Cities of Western Asia Minor. Oxford: Oxford University Press, 2002.",
  "Eckstein, Arthur. Mediterranean Anarchy, Interstate War, and the Rise of Rome. Berkeley: University of California Press, 2006.",
  "Eckstein, Arthur. Rome Enters the Greek East. From Anarchy to Hierarchy in the Hellenistic Mediterranean 230-170 BC. Oxford: Wiley-Blackwell Publishing, 2008.",
  "Fronda, Michael P. Between Rome and Carthage: Southern Italy during the Second Punic War. Cambridge: Cambridge University Press, 2010.",
  "Gruen Eric. The Hellenistic World and the Coming of Rome. Berkeley: University of California Press, 1986.",
  "Howgego, Christopher, Volker Heuchert, and Andrew Burnett, eds. Coinage and Identity in the Roman Provinces. Oxford: Oxford University Press, 2008.",
  "Ma, John, Nikolaos Papazarkadas and Robert Parker, eds. Interpreting the Athenian Empire. London: Duckworth Publishing, 2009.",
  "Raaflaub, Kurt. \"City-State, Territory, and Empire.\" In City-States in Classical Antiquity and Medieval Italy, edited by Anthony Molho, Julia Emlen, and Kurt Raaflaub. Ann Arbor: University of Michigan Press (1991): 565-88.",
  "Richardson, John. The Language of Empire: Rome and the Idea of Empire from the Third Century BC to the Second Century AD. Cambridge: Cambridge University Press, 2009.",
  "Scheidel, Walter, Ian Morris, and Richard P. Saller, eds. The Cambridge Economic History of the Graeco-Roman World. Cambridge: Cambridge University Press, 2007.",
  "Scott, Sarah. \"Local Responses to Roman Imperialism.\" American Journal of Archaeology 114, no. 3 (July 2010): 556-61.",
  "Stroud, Ronald S. The Athenian Empire on Stone: David M. Lewis Memorial Lecture Oxford 2006. Athens: Helléniké Epigraphiké Hetaireia, 2006.",
  "Ando, Clifford. The Matter of the Gods: Religion and the Roman Empire. The Transformation of the Classical Heritage. Berkeley: University of California Press, 2008.",
  "Beard, Mary and John North, eds., Pagan Priests: Religion and Power in the Ancient World. London: Duckworth, 1990.",
  "Belayche, Nicole. \"Religious Actors in Daily Life: Practices and Related Beliefs.\" In A Companion to Roman Religion, edited by Jörg Rüpke. Oxford: Wiley-Blackwell Publishing, 2007.",
  "Buc, Phillipe. Dangers of Ritual: Between Early Medieval Texts and Social Scientific Theory. Princeton, NJ: Princeton University Press, 2009.",
  "Burkert, Walter. Greek Religion. Translated by John Raffan. Cambridge, MA: Harvard University Press, 1985.",
  "Chaniotis, Angelos, ed. Ritual Dynamics in the Ancient Mediterranean: Agency, Emotion, Gender, Representation. Heidelberger althistorische Beiträge und epigraphische Studien (HABES) 49. Stuttgart: Franz Steiner Verlag, 2011.",
  "Durkheim, Émile. The Elementary Forms of Religious Life, 5th ed. Translated by Karen E Fields. Glencoe, IL: Free Press, 1995.",
  "Feeney, Denis. Literature and Religion at Rome: Cultures, Contexts, and Beliefs. Cambridge: Cambridge University Press, 1998.",
  "Koziol, Geoffrey. \"The Dangers of Polemic: Is Ritual Still an Interesting Topic of Historical Study?\" Early Medieval Europe 11, no. 4 (January 2002): 367-88.",
  "Kaizer, Ted. \"Religion in the Roman East.\" In A Companion to Roman Religion, edited by Jörg Rüpke. Oxford: Wiley-Blackwell Publishing, 2007.",
  "Melfi, Milena. \"Ritual Spaces and Performances in the Asklepieia of Roman Greece.\" The Annual of the British School at Athens 105 (2010): 317-38.",
  "Mikalson, Jon D. “Religion in the Attic Demes.” The American Journal of Philology 98, no. 4 (December 1, 1977): 424–435.",
  "Price, Simon R.F. \"Between Man and God: Sacrifice in the Roman Imperial Cult.\" Journal of Roman Studies 70 (1980): 28-43.",
  "Price, Simon R.F. Rituals and Power: The Roman Imperial Cult in Asia Minor. Cambridge: Cambridge University Press, 1984.",
  "Price, Simon R.F. \"Gods and Emperors: The Greek Language of Imperial Cult.\" Journal of Hellenic Studies 104 (1984): 79-95.",
  "Sourvinou-Inwood, C. \"What is Polis Religion?\" in Oxford readings in Greek religion. Edited by R.G.A. Buxton, 13-37. Oxford: Oxford University Press, 2000.",
  "Sourvinou-Inwood, C. \"Further aspects of Polis Religion.\" in Oxford readings in Greek religion. Edited by R.G.A. Buxton, 38-55. Oxford: Oxford University Press, 2000.",
  "Smith, Jonathan Z. ”The Domestication of Sacrifice.” In Violent Origins: Walter Burkert, Rene Girard, and Jonathan Z. Smith on Ritual Killing and Cultural Formation, edited by Robert G. Hamerton-Kelly, 191-205. Stanford: Stanford University Press, 1987.",
  "Steinbock, Bernd. Social Memory in Athenian Public Discourse: Uses and Meanings of the Past. Ann Arbor: University of Michigan Press, 2013.",
  "Stowers, S. “Greeks Who Sacrifice and Those Who Do Not: Toward an Anthropology of Greek Religion.” in The Social World of the First Christians: Essays in Honor of Wayne A. Meeks, edited by L. Michael White and O. Larry Yarbough. Minneapolis: Fortress Press, 1995.",
  "Sokolowski, Franciszek. Lois sacrées des Cités grecques. Paris: De Boccard, 1969.",
  "Alcock, Susan, and Robin Osborne, eds. Placing the Gods: Sanctuaries and Sacred Space in Ancient Greece. Clarendon Paperbacks. Oxford: Oxford University Press, 1991.",
  "Alcock, Susan, Terence N. D'Altroy, Kathleen Morrison, Carla M. Sinopoli, eds. Empires: Perspectives from Archaeology and History. Cambridge: Cambridge University Press, 2001.",
  "Alcock, Susan. Archaeologies of the Greek Past: Landscape Monuments and Memories. Cambridge: Cambridge University Press, 2002.",
  "Alcock, Susan and Robin Osborne, eds. Classical Archaeology. Blackwell Studies in Global Archaeology. Oxford: Wiley-Blackwell Publishing, 2007.",
  "Bender, Barbara, Sue Hamilton, and Chris Tilley. Stone Worlds: Narrative and Reflexivity in Landscape Archaeology. Walnut Creek, CA: Left Coast Press, 2007.",
  "Bentley, Alexander and Herbert Maschner, eds.. Complex Systems and Archaeology: Empirical and Theoretical Applications. Salt Like City: University of Utah Press, 2003.",
  "Christophe, Pébarthe. Cité, démocratie, et écriture. Histoire de l'alphabétisation d'Athènes à l'époque classique. Paris: De Boccard, 2006.",
  "Corinna Riva and Nicolas C. Vella, eds. Debating Orientalization: Multidisciplinary Approaches to Change in the Ancient Mediterranean. Monographs in Mediterranean Archaeology 10. Sheffield, UK. Equinox Publishing, 2010.",
  "Edwards, Douglas and C. Thomas McCollough. The Archaeology of Difference: Gender, Ethnicity, Class, and the \"Other\" in Antiquity. Studies in Honor of Eric M. Meyers. Annual of the American Schools of Oriental Research, 60/61. Boston: American Schools of Oriental Research, 2005.",
  "Forbes, Hamish. Meaning and Identity in a Greek Landscape: An Archaeological Ethnography. Cambridge: Cambridge University Press, 2007.",
  "Foxhall, Lin. Cultivation in Ancient Greece: Seeking the Ancient Economy. Oxford: Oxford University Press, 2007.",
  "Harris, William V. Ancient Literacy. Cambridge, MA: Harvard University Press, 1989.",
  "Nelson, Robert S., and Margaret Olin, eds. Monuments and Memory, Made and Unmade. Chicago: University of Chicago Press, 2004.",
  "Papalexandrou, Nassos. \"Beyond the Acropolis: New Installations of Greek Antiquities in Athenian Museums.\" American Journal of Archaeology 114, no. 3 (July 2010): 549-556.",
  "Thomas, Rosalind. Oral Tradition and Written Record in Classical Athens. Cambridge Studies in Oral and Literate Culture. Cambridge: Cambridge University Press, 1992.",
  "Thomas, Rosalind. Literacy and Orality in Ancient Greece. Cambridge: Cambridge University Press, 1992.",
  "Wright, James C. “The Spatial Configuration of Belief: The Archaeology of Mycenaean Religion.” In Placing the Gods: Sanctuaries and Sacred Space in Ancient Greece, edited by Susan E. Alcock and Robin Osbourne, 37-76. Clarendon Paperbacks. Oxford: Oxford University Press, 1999.",
  "Amory, Patrick. People and Identity in Ostrogothic Italy, 489-554. Cambridge Studies in Medieval Life and Thought 4, no. 33. Cambridge: Cambridge University Press, 1997.",
  "Anderson, Benedict. Imagined Communities: Reflections on the Origin and Spread of Nationalism. London: Verso, 2006.",
  "Benwell, B. and E. Stokoe. Discourse and Identity. Edinburgh: Edinburgh University Press, 2006.",
  "Bondi, L. Locating Identity Politics. In Place and the Politics of Identity. Edited by M. Keith and S. Pile, 84-101. London: Routledge, 1993.",
  "Brubaker, R. and F. Cooper. \"Beyond Identity.\" Theory and Society 29 (2000): 1-47.",
  "Burke, P.J. \"The Self: Measurement Requirements from an Interactional Perspective.\" Social Psychology Quarterly 43, no. 1 (1980): 18-29.",
  "Burke, P.J. \"Identity Processes and Social Stress.\" American Sociological Review 56 (1991): 836-49.",
  "Burke, P.J. and D.C. Reitzes. \"The Link between Identity and Role Performance.\" Social Psychology Quarterly 44, no. 2 (1981): 83-92.",
  "Conant, Jonathan. Staying Roman: Conquest and Identity in Africa and the Mediterranean, 439-700. Cambridge Studies in Medieval Life and Thought 4, no. 82. Cambridge: Cambridge University Press, 2012.",
  "Fiske, S.T., and S.E. Taylor. Social Cognition. New York: McGraw-Hill, 1991.",
  "Florin, Curta. The Making of Slavs: History and Archaeology of the Lower Danube Region c.500-700. Cambridge Studies in Medieval Life and Thought 4, no. 52. Cambridge: Cambridge University Press, 2007.",
  "Foote, N.N. \"Identification as the Basis for a Theory of Motivation\" American Sociological Review 26 (1951): 14-21.",
  "Geschiere, Peter. The Perils of Belonging: Autochthony, Citizenship, and Exclusion in Africa and Europe. Chicago: University of Chicago Press, 2009.",
  "Heather, Peter. The Goths. The Peoples of Europe. Oxford: Wiley-Blackwell, 1998.",
  "Hogg, M.A., D.J. Terry, and K.M. White. \"A Tale of Two Theories: A Critical Comparison of Identity Theory with Social Identity Theory.\" Social Psychology Quarterly 58, no. 4 (1995): 255-69.",
  "Hollinger, David A. \"From Identity to Solidarity.\" Daedalus 135, no. 4 (Fall 2006): 23-31.",
  "James, Edward. The Franks. The Peoples of Europe. Oxford: Wiley-Blackwell, 1988.",
  "Jones, Christopher. \"Ancestry and Identity in the Roman Empire.\" In Local Knowledge and Microidentities in the Imperial Greek World: Greek Culture in the Roman World, edited by Tim Whitmarsh, 111-24. Cambridge: Cambridge University Press, 2010.",
  "Kaldellis, Anthony. Hellenism in Byzantium: The Transformations of Greek Identity and the Reception of the Classical Tradition. Greek Culture in the Roman World. Cambridge: Cambridge University Press, 2008.",
  "Kaldellis, Anthony. \"The Byzantine Role in the Making of the Corpus of Classical Greek Historiography: A Preliminary Investigation.\" Journal of Hellenic Studies 132 (2012): 71-85.",
  "Kaplan, D.H. and G.H. Herb. \"A Question of Identity.\" In Nested Identities: Nationalism, Territory, and Scale. Edited by G.H. Herb and D.H. Kaplan, 1-8. Lanham, MD: Rowman and Littlefield, 1999.",
  "Keith, M. and S. Pile, eds. Place and the Politics of Identity. London: Routledge, 1993.",
  "Malkin, Irad, ed. Ancient Perceptions of Greek Ethnicity. Center for Hellenic Studies Colloquia 5. Washington, DC: Center for Hellenic Studies, 2001.",
  "Martin Pitts \"The Emperor's New Clothes? The Utility of Identity in Roman Archaeology\" American Journal of Archaeology 114, no. 4 (October 2007): 693-713.",
  "Norquay, Naomi. \"Identity and Forgetting.\" The Oral History Review 26, no. 1 (Winter-Spring 1999): 1-21.",
  "Oliver, James H. \"Panachaeans and Panhellenes.\" Hesperia 47, no. 2 (1978): 185-91.",
  "Shoemaker, Sydney. \"Identity & Identities.\" Daedalus 135, no. 4 (Fall 2006): 40-8.",
  "Siapkes, Johannes. Heterological Ethnicity: Conceptualizing Identities in Ancient Greece. Uppsala Studies in Ancient Mediterranean and Near Eastern Civilizations 27. Uppsala: Uppsala Universitet, 2003.",
  "Sommers, M.R. \"The Narrative Construction of Identity: A Relational and Network Approach.\" Theory and Society 23 (1994): 605-49.",
  "Stoler, Ann Laura. Imperial Debris: On Ruins and Ruination. Durham, NC: Duke University Press, 2013.",
  "Whitmarsh, Tim, ed. Local Knowledge and Microidentities in the Imperial Greek World. Greek Culture in the Roman World. Cambridge: Cambridge University Press, 2010.",
  "Barabási, Albert-László. Linked: The New Science of Networks. Cambridge, Mass: Perseus Books, 2003.",
  "Boissevain, Jeremy. Friends of Friends: Networks, Manipulators and Coalitions. New York: St. Martin's Press, 1974.",
  "Boissevain, Jeremy, and J. Clyde Mitchell. Network Analysis: Studies in Human Interaction. The Hague: Mouton Publishers, 1973.",
  "Buchanan, Mark. Nexus: Small Worlds and the Groundbreaking Science of Networks. New York: W.W. Norton, 2002.",
  "Cilliers, P. Complexity and Postmodernism: Understanding Complex Systems. London: Routledge, 1998.",
  "Degenne, Alain, and Michel Forsé. Introducing Social Networks. Introducing Statistical Methods Series. London: SAGE Publications, 1999.",
  "Freeman, Linton. The Development of Social Network Analysis. Empirical Press: Vancouver, 2004.",
  "Perliger, Arie and Ami Pedahzur. \"Social Network Analysis in the Study of Terrorism and Political Violence.\" Political Science and Politics 44, no. 1 (2011): 45-50.",
  "Siegel, David A. \"Social Networks in Comparative Perspective.\" Political Science and Politics 44, no. 1 (2011): 51-4.",
  "Watts, D.J. and S.H. Strogatz. \"Collective Dynamics of 'Small-World' Networks.\" Nature 393 (1998): 440-2.",
  "Aleshire, Sarah B. “Towards a Definition of ‘State Cult’ for Ancient Athens.” In Ancient Greek Cult Practice from the Epigraphical Evidence: Proceedings of the Second International Seminar on Ancient Greek Cult, Acta Instituti Atheniensis Regni Sueciae 8, edited by Robin Hägg, 9-16. Stockholm: Svenska Institutet i Athen, 1994.",
  "Aleshire, Sarah B. \"The Demos and the Priests.\" In Ritual, Finance, Politics, Athenian Democratic Accounts Presented to D.M. Lewis., edited by Robin Osborne and Simon Hornblower, 325-38. Oxford: Clarendon Press, 1994.",
  "Clinton, Kevin. “IG I2 5, the Eleusinia, and the Eleusinians.” The American Journal of Philology 100, no. 1 (April 1, 1979): 1–12.",
  "Clinton, Kevin. Myth and Cult: the Iconography of the Eleusinian Mysteries. Acta Instituti Atheniensis Regni Sueciae 80. Stockholm: Svenska Institutet i Athen, 1992.",
  "Clinton, Kevin. \"The Sanctuary of Demeter and Kore at Eleusis.\" In Greek Sanctuaries, New Approaches, edited by N. Marinatos and R. Hägg. London: Routledge, 1993.",
  "Feaver, D.G. \"Historical Developments in the Priesthoods of Athens.\" Yale Classical Studies 15 (1957): 123-58.",
  "Foucart, Paul. Les mystères d'Éleusis. Paris: Picard, 1914.",
  "Gagné, Renaud. “Mystery Inquisitors: Performance, Authority, and Sacrilege at Eleusis.” Classical Antiquity 28, no. 2 (October 1, 2009): 211–247.",
  "Gagné, Renaud, and Miguel Herrero. “Themis at Eleusis: Clement of Alexandria, ‘Protrepticus’ 2.22.5.” The Classical Quarterly 59, no. 1 (May 1, 2009): 289–293.",
  "Garland, R. “Priests and Power in Classical Athens.” In Pagan Priests: Religion and Power in the Ancient World, edited by Mary Beard and John North, 73-94. London: Duckworth, 1990.",
  "Gerding, Hendrick. \"The Erechtheion and the Panathenaic Procession.\" American Journal of Archaeology 110, no. 3 (July 2006): 389-401.",
  "Giraud, D. “The Greater Propylaia at Eleusis, a Copy of Mnesikles’ Propylaia.” .” In The Greek Renaissance in the Roman Empire: Papers from the Tenth British Museum Colloquium, Bulletin Supplement, edited by Susan Walker and Averil Cameron, 69-75. London: University of London Institute of Classical Studies, 1989.",
  "Hawke, Jason. \"The City Eleusinion and the Kalliad Kerykes.\" Ancient World 39, no. 2 (2008): 108-124.",
  "Horset, Marietta. Civic Priests Cult Personnel in Athens from the Hellenistic Period to Late Antiquity. Religionsgeschichtliche Versuche und Vorarbeiten, 58. Berlin: Walter de Gruyter, 2012.",
  "Humphreys, Sarah C. The Strangeness of the Gods: Historical Perspectives on the Interpretation of Athenian Religion. Oxford: Oxford University Press, 2004.",
  "Kearns, Emily. The Heroes of Attica. Bulletin of the Institute of Classical Studies Supplement 57. London: Institute of Classical Studies, 1989.",
  "Kerényi, Carl. Eleusis: Archetypal Image of Mother and Daughter. Princeton: Princeton University Press, 1991.",
  "Mikalson, Jon D. Religion in Hellenistic Athens. Berkeley: University of California Press, 1998.",
  "Mylonas, G.E. Eleusis and the Eleusinian Mysteries. Princeton, NJ: Princeton University Press, 1961.",
  "Niku, M. The Official Status of Foreign Residents in Athens, 322-120 BC. Papers and Monographs of the Finnish Institute at Athens. Helsinki: Finnish Institute at Athens, 2007.",
  "Nulton, P.E. The Sanctuary of Apollo Hypoakraios and Imperial Athens. Providence, RI: Center for Old World Archaeology and Art, Brown University, 2003.",
  "Osborne, Robin and Simon Hornblower, eds. Ritual, Finance, Politics. Athenian Democratic Accounts Presented to David Lewis. Oxford: Clarendon Press, 1994.",
  "Padgug, Robert A. \"Eleusis and the Union of Attika.\" Greek, Roman, and Byzantine Studies 13, no. 2 (1974): 135-50.",
  "Parke, Herbert .W. Festivals of the Athenians. Aspects of Greek and Roman Life. London: Cornell University Press, 1977.",
  "Parker, Robert. Athenian Religion: A Brief History. Clarendon Paperbacks. Oxford: Oxford University Press, 1996.",
  "Parker, Robert. Polytheism and Society at Athens. Oxford: Oxford University Press, 2007.",
  "Rigsby, Kent. \"Apollo and the Archons.\" in Studies in Greek Epigraphy and History in Honor of Stephen V. Tracy. Études Ausonius Institute 26. Edited by Gary Reger, F.X. Ryan, and Timothy F. Winters, 171-6. Paris: De Boccard, 2010.",
  "Robertson, Noel. \"The Riddle of the Arrhephoria at Athens.\" Harvard Studies in Classical Philology 87 (1983): 241-88.",
  "Robertson, Noel. \"The Two Processions to Eleusis and the Program of the Mysteries.\" American Journal of Philology 119, no. 4 (1998): 547-575.",
  "Sourvinou-Inwood, Christina.  “Reconstructing Change: Ideology and the Eleusinian Mysteries.”  In Inventing Ancient Culture: Historicism, Periodization, and the Ancient World, edited by M. Golden and P. Toohey, 132-64. London: Routledge, 1997.",
  "Barnard, Bailey. “Euergetism and Gift-Giving at Eleusis: A Case Study of Ancient Patronage Structures.” M.A. Thesis, University of Nebraska-Lincoln, 2011. http://digitalcommons.unl.edu/artstudents/20.",
  "Bayliss, Andrew J. After Demosthenes: The Politics of Early Hellenistic Athens. London: Continuum, 2011.",
  "Frösén, Jaakko. Early Hellenistic Athens: Symptoms of a Change. Helsinki: Suomen Ateenan-Instituutin Säätiö, 1997.",
  "Kosmetatou, Elizabeth. “Rhoxane’s Dedications to Athena Polias.” Zeitschrift für Papyrologie und Epigraphik 146 (January 1, 2004): 75–80.",
  "Lape, Susan. Reproducing Athens: Menander's Comedy, Democratic Cuture, and the Hellenistic City. Princeton, NJ: Princeton University Press, 2004.",
  "Habicht, Christian. \"The Role of Athens in the Reorganization of the Delphic Amphictony after 189 B.C.\" Hesperia 56, no. 1 (1987): 59-71.",
  "Habicht, Christian. \"Athens and the Attalids in the Second Century B.C.\" Hesperia 59, no. 3 (1990): 561-77.",
  "Habicht, Christian. “Athens and the Ptolemies.” Classical Antiquity 11, no. 1 (April 1, 1992): 68–90.",
  "Habicht, Christian. Athens from Alexander to Antony. Translated by Deborah Lucas Schneider. Cambridge, MA: Harvard University Press, 1997.",
  "MacKendrick, P. (1969). Athenian Aristocracy, 399 to 31 B.C. Martin Classical Lectures 23. Cambridge, MA: Harvard University Press, 1969.",
  "Oetjen, Roland. “War Demetrios von Phaleron, der Jüngere, Kommissar des Königs Antigonos II. Gonatas in Athen?” Zeitschrift für Papyrologie und Epigraphik 131 (January 1, 2000): 111–117.",
  "Oliver, Graham J. War, Food, and Politics in Early Hellenistic Athens. Oxford: Oxford University Press, 2007.",
  "Pakkanen, Petra. Interpreting Early Hellenistic Religion: A Study Based on the Mystery Cult of Demeter and the Cult of Isis. Helsinki: Suomen Ateenan-Instituutin Säätiö, 1996.",
  "Vogeikoff-Brogan, Natalia. \"Late Hellenistic Pottery in Athens: A New Deposit and Further Thoughts on the Association of Pottery and Societal Change.\" Hesperia 69, no. 69 (2000): 293-333.",
  "Zelnick-Abramovitz, Rachel. “Supplication and Request: Application by Foreigners to the Athenian Polis.” Mnemosyne 51, no. 5 (October 1, 1998): 554–573.",
  "Day, John. An Economic History of Athens Under Roman Domination. Greek History. New York: Columbia University Press, 1942.",
  "Clinton, Kevin. The Sacred Officials of the Eleusinian Mysteries. Transactions of the American Philosophical Society, New Series 64, no. 3. Philadelphia: The American Philosophical Society, 1974.",
  "Follet, S. \"Constitutions athéniennes d'époque romaine. Quelques nouvelles lectures.\" in XI Congresso internazionale di epigrafia greca e latina, Roma 18-24 settembre 1997. Rome: Edizioni Quasar, 1999.",
  "Geagan, Daniel. The Athenian Constitution After Sulla. Hesperia Supplements 12. Princeton, NJ: American School of Classical Studies at Athens, 1967.",
  "Geagan, Daniel. \"Ordo Areopagitarum Atheniensium.\" in ΦΟΡΟΣ: Tribute to Benjamin Dean Merritt. Edited by Donald William Bradeen and and Malcom Francis MacGregor, 51-6. Locus Valley, NY: J.J. Augustin, 1974.",
  "Geagan, Daniel. \"The Third Hoplite Generalship of Antipatros of Phlya.\" American Journal of Philology 100, no.1 (1979): 59-68.",
  "Geagan, Daniel. “Tiberius Claudius Novius, the Hoplite Generalship and the Epimeleteia of Free City of Athens.” American Journal of Philology 100, no. 2 (1979): 279-87.",
  "Geagan, Daniel. \"Roman Athens: Some Aspects of Life and Culture. I 86 B.C. - A.D. 267.\" In Aufstieg und Niedergang der römischen Welt 34. Berlin: Walter de Gruyter, 1993-8.",
  "Habicht, Christian. \"Salamis in der Zeit nach Sulla.\" Zeitschrift für Papyrologie und Epigrafik 111 (1996): 79-87.",
  "Kapetanopoulos, Elias. \"Some Observations on Roman Athens.\" Zeitschrift für Alte Geschichte 19, no. 5 (1970): 561-4.",
  "Notopoulos, James A. “The Method of Choosing Archons in Athens under the Empire.” The American Journal of Philology 65, no. 2 (January 1, 1944): 149–166.",
  "Oliver, J. “The Sacred Gerusia.” Hesperia Supplements 6 (1941): 1-204.",
  "Oliver, J. The Athenian Expounders of the Sacred and Ancestral Law. Baltimore: Johns Hopkins Press, 1950.",
  "Oliver, J. “Areopagites.” Hesperia 27, no. 1 (1958): 38-46.",
  "Oliver, J. “From Gennetai to Curiales.” Hesperia 49 (1980): 30-56.",
  "Oliver, J. The Civic Tradition and Roman Athens. Baltimore: Johns Hopkins Press, 1983.",
  "Tracy, S.V. \"Athens in 100 B.C.\" Harvard Studies in Classical Philology 83 (1979): 213-235.",
  "Wilson, Peter. The Athenian Institution of the Khoregia: The Chorus, the City, and the Stage. Cambridge: Cambridge University Press, 2000.",
  "Cromey, R.D. “Apollo Patroos and the Phratries.” L’Antiquité Classique 75 (January 1, 2006): 41–69.",
  "Donlan, Walter. “The Social Groups of Dark Age Greece.” Classical Philology 80, no. 4 (October 1985): 293-308.",
  "Dow, Sterling. \"Athletic Agones in Roman Athens Honoring Tykhe Poleos.\" The American Journal of Philology 100, no. 1 (1979): 31-44.",
  "Ferguson, William Scott. “The Athenian Phratries.” Classical Philology 5, no. 3 (July 1, 1910): 257–284.",
  "Fröhlich, P. Groupes et associations dans les cités grecques (IIIe siècle av. J.-C. - IIe siècle apr. J.-C.). Hautes Études du monde gréco-romain 49. Geneva: Droz, 2012.",
  "Hedrick, Charles Jr. \"Phratry Shrines of Attica and Athens.\" Hesperia 60, no. 2 (1991): 241-68.",
  "Humphreys, S.C. \"Public and Private Interests in Classical Athens.\" Classical Journal 73, no. 2 (December 1977): 97-104.",
  "Humphreys, S. C. “Phrateres in Alopeke, and the Salaminioi.” Zeitschrift für Papyrologie und Epigraphik 83 (January 1, 1990): 243–248.",
  "Jones, Nicholas F. The Associations of Classical Athens: The Response to Democracy. Oxford: Oxford University Press, 1999.",
  "Jones, Nicholas F. “The Athenian Phylai as Associations: Disposition, Function, and Purpose.” Hesperia 64, no. 4 (October 1, 1995): 503–542.",
  "Kloppenborg, John S. Voluntary Associations in the Graeco-Roman World. London: Routledge, 1996.",
  "Kloppenborg, John S., and Richard S. Ascough. Greco-Roman Associations Texts, Translations, and Commentary. Vol. 1, Attica, Central Greece, Macedonia, Thrace. Beihefte zur Zeitschrift für die neutestamentlich Wissenschaft und die Kunde der älteren Kirche 181. Berlin: Walter de Gruyter, 2011.",
  "Lambert, Stephen. Phratries of Attica. Ann Arbor: University of Michigan Press, 1993.",
  "Lambert, S. D. “Notes on Two Attic ‘Horoi’: And Some Corrigenda to ‘The Phratries of Attica.’” Zeitschrift für Papyrologie und Epigraphik 110 (January 1, 1996): 77–83.",
  "Lambert, Stephen. \"IGII2 2345, Thiasioi of Herakles and the Salaminioi Again.\" Zeitschrift für Papyrologie und Epigrafik 125 (1999): 93-130.",
  "Nijf, Onno van. The Civic World of Professional Associations in the Roman East. Amsterdam, J.C. Gieben, 1997.",
  "Raubitschek, A.E. \"A New Attic Club (ERANOS).\" J. Paul Getty Museum Journal 9 (1981): 93-8.",
  "Traill, John S. “The Political Organization of Attica: A Study of the Demes, Trittyes, and Phylai, and Their Representation in the Athenian Council.” Hesperia Supplements 14 (January 1, 1975): i–169. doi:10.2307/1353928.",
  "Wade-Gery, H.T. \"Eupatridai, Archons, and the Areopagus.\" The Classical Quarterly 25, no. 1 (1931): 1-11.",
  "Blok, Josine H., and Stephen D. Lambert. “The Appointment of Priests in Attic gene.” Zeitschrift für Papyrologie und Epigraphik 169 (January 1, 2009): 95–121.",
  "Bourriot, Felix. Recherches sur la nature du genos: Étude d’histoire sociale athénienne – périodes archaïque et classique. Lille: Université Lille, 1976.",
  "Ferguson, W.S. “The Salaminioi of Heptaphylai and Sounion.” Hesperia 7, no. 1 (1938): 1-74.",
  "Fustel de Coulanges, Numa Denis. La Cité Antique: Étude sur le culte, le droit, les institutions de la Grèce et de Rome. Paris, 1864.",
  "Geagan, Daniel. “The Great Catalogue from the City Eleusinion.” Zeitschrift für Papyrologie und Epigrafik 33 (1979): 93-115.",
  "Grijalvo, Elena Muñiz. \"Elites and Religious Change in Roman Athens.\" Numen 52, no. 2 (2005): 255-282.",
  "Humphreys, Sarah C. \"Phratries in Alopeke, and the Salaminioi.\" Zeitschrift für Papyrologie und Epigrafik 83 (1990): 243-8.",
  "Lambert, S. D. “The Attic Genos.” The Classical Quarterly 49, no. 2 (January 1, 1999): 484–489.",
  "Lambert, Stephen D. “The Attic Genos Salaminioi and the Island of Salamis.” Zeitschrift für Papyrologie und Epigraphik 119 (January 1, 1997): 85–106.",
  "Lambert, Stephen D. “Aglauros, the Euenoridai and the Autochthon of Atlantis.” Zeitschrift für Papyrologie und Epigraphik 167 (January 1, 2008): 22–26.",
  "Lambert, S. D. “The Attic ‘Genos’ Bakchiadai and the City Dionysia.” Historia: Zeitschrift für Alte Geschichte 47, no. 4 (December 1, 1998): 394–403.",
  "Rhodes, P.J. \"Deceleans and Demotionidae Again.\" in Classical Quarterly 47, no. 1 (1997): 109-20.",
  "Roussel, Dénis. Tribu et cite: Études sur les groupes sociaux dans les cités grecques aux époques archaique et classique. Paris: Annales littéraires de l’université de Besançon 193, 1976.",
  "Rutherford, Ian. \"Amphikleidai of Sicilian Naxos\" Zeitschrift für Papyrologie und Epigrafik 122 (1998): 81-9.",
  "Schiller, Alex K. \"Multiple Gentile Associations and the Athenian Response to Roman Domination.\" Historia: Zeitschrift für Alte Geschichte 55, no. 3 (2006): 264-84.",
  "Sherwin-White, Susan M. Ancient Cos. An Historical Study from the Dorian Settlement to the Imperial Period. Hypomnemata 51. Gottingen: Vandenhoeck & Ruprecht, 1978.",
  "Badian, E. \"Rome, Athens, and Mithridates.\" American Journal of Ancient History 1 (1976): 105-28.",
  "Bugh, Glenn Richard. “Athenion and Aristion of Athens.” Phoenix 46, no. 2 (July 1, 1992): 108–123.",
  "Bullock, Anne N. “Eleusis as Palimpsest: Postcolonial Theory and the Politics of Religion in Roman Greece.” PhD, Emory University, 2010.",
  "Culley, Gerald R. “The Restoration of Sanctuaries in Attica: I.G., II2, 1035.” Hesperia 44, no. 2 (April 1, 1975): 207–223.",
  "Dow, S. \"A Leader of the Anti-Roman Party in Athens in 88 B.C.\" Classical Philology 37 (1942): 311-4.",
  "Follet, S. \"Damnatio memoriae et crise de 88/87 BC.\" In Studies in Greek Epigraphy and History in Honor of Stephen V. Tracy. Études Ausonius Institute 26. Edited by Gary Reger, F.X. Ryan, and Timothy F. Winters, 161-170. Paris: De Boccard, 2010.",
  "Geagan, Daniel. “The Athenian Elite: Romanization, Resistance, and the Exercise of Power.” in The Romanization of Athens. Michael C. Hoff, Susan I. Rotroff, eds. Oxford: Oxbow Books, 1997.",
  "Habicht, C. \"Zur Geschichte Athens in der Zeit Mithridates VI. Der eponyme Archon im Jahre der ,Anarchie‛ (88/7).\" Chiron 6 (1976): 127-35.",
  "Hoff, Michael C. “Civil Disobedience and Unrest in Augustan Athens.” Hesperia 58 (1989): 267-76.",
  "Hoff, Michael C. \"Augustus, Apollo, and Athens.\" Museum Helveticum 49 (1992): 223-32.",
  "Hoff, Michael C. and Susan L. Rotroff, eds. Romanization of Athens. Oxford: Oxbow Books, 1997.",
  "Iversen, Paul A. \"A Prytany Dedication from Athens Found at Corinth.\" Hesperia 79, no. 3 (2010): 417-22.",
  "Kapetanopoulos, Elias. \"The Reform of the Athenian Constitution under Hadrian.\" Horos 10-12 (1998): 215-37.",
  "Kapteanopoulos, Elias. \"Romanitas and the Athenian Prytaneis.\" Archaiologika Ephemeris 1981: 23-36.",
  "Kapteanopoulos, Elias. \"Hadrianis and the Boule of Five Hundred.\" Balkan Studies 22 (1981): 147-65.",
  "Kelly, Leslie Caroline. “Identity and Cult in Roman Imperial Athens.” Ph.D. Dissertation, University of Pennsylvania, 2010. http://repository.upenn.edu/dissertations/AAI3447099.",
  "Manchado, Javier Verdejo and Borja Antela-Bernárdez. \"A Crown for Onaso and the Archon Athenion.\" Zeitschrift für Papyrologie und Epigrafik 177 (2011): 91-6.",
  "McGing, B.C. The Foreign Policy of Mithridates VI Eupator, King of Pontos. Leiden: Brill, 1986.",
  "Oliver, James H. \"Livia as Artemis Boulaia at Athens.\" Classical Philology 60, no. 3 (1965):  179.",
  "Oliver, James H. \"Philosophers and Procurators, Relatives of the Aemilius Juncus of Vita Commodi.\" Hesperia 36, no. 1 (1967): 42-56.",
  "Oliver, James H. \"The Diadoche at Athens under Humanistic Emperors.\" The American Journal of Philology 98, no.2 (1977): 160-78.",
  "Papalas, Anthony J. \"Marcus Aurelius and Three Sophists.\" Aevum 53, no. 1 (1979): 88-93.",
  "Robertson, Noel. \"A Point of Precedence at Plataia: The Dispute Between Athens and Sparta Over Leading the Procession.\" Hesperia 55, no. 1 (1986): 88-102.",
  "Tod, M. “Greek Inscriptions from Macedonia.” Journal of Hellenic Studies 42, no. 2 (1922): 167-83.",
  "Abramson, H. \"The Olympieion in Athens and Its Connections with Rome.\" California Studies in Classical Antiquity 7 (1974):1-25.",
  "Armstrong, David. \"Gallienus in Athens, 264.\" Zeitschrift für Papyrologie und Epigrafik 70 (1987): 235-58.",
  "Benjamin, Anna S. \"The Altars of Hadrian in Athens and Hadrian's Panhellenic Program.\" Hesperia 32, no. 1 (1963): 57-86.",
  "Benjamin, Anna S. \"Two Dedications in Athens to Archons of the Panhellenion.\" Hesperia 37, no. 3 (1968): 338-44.",
  "Birley, Anthony R. \"Hadrian and Greek Senators.\" Zeitschrift für Papyrologie und Epigrafik 116 (1997): 209-45.",
  "Boatwright, Mary. \"Further Thoughts on Hadrianic Athens.\" Hesperia 52, no. 2 (1983): 173-6.",
  "Boatwright, Mary. Hadrian and the Cities of the Roman Empire. Princeton, NJ: Princeton University Press, 2002.",
  "Byrne, Sean. \"Early Roman Athenians.\" in Lettered Attica: A Day of Attic Epigraphy. Proceedings of the Athens Symposium, 8 March 2000. Edited by D. Jordan and J. Traill. Toronto: Canadian Archaeological Institute at Athens, 2003.",
  "Clinton, Kevin. “Hadrian’s Contribution to the Renaissance of Eleusis.” In The Greek Renaissance in the Roman Empire: Papers from the Tenth British Museum Colloquium, Bulletin Supplement, edited by Susan Walker and Averil Cameron, 56-68. London: University of London Institute of Classical Studies, 1989.",
  "Clinton, Kevin. “The Eleusinian Mysteries: Roman Initiates and Benefactors, Second Century B.C. to A.D. 207.” In Aufstieg Und Niedergang Der Romischen Welt 18, no. 2., edited by Wolfgang Haase, 1499-1539. Berlin: Walter de Gruyter, 1989.",
  "Clinton, Kevin. “Eleusis and the Romans.” In The Romanization of Athens: Proceedings of an International Conference held at Lincoln, Nebraska (April 1996),  Oxbow Monographs 94, edited by Michael C. Hoff and Susan I. Rotroff, 161-82. Oxford: Oxbow, 1997.",
  "Clinton, Kevin. “Eleusis from Augustus to the Antonines: Progress and Problems.” In Atti dell'XI Congresso Internazionale di Epigrafia Greca e Latina, edited by Silvio Panciera, 93-102. Rome: Edizioni Quasar, 1999.",
  "Fishwick, D. \"Our First High Priest: A Gallic Knight at Athens.\" Epigraphica 60 (1998): 83-112.",
  "Follet, S. and D. Peppas-Delmousou. \"La légende de Thésée sous l'empereur Commode d'après le discours d'un éphèbe athénien.\" Mélanges en l'honneur d'Yvette Duval. Paris: De Boccard, 2000.",
  "Foucart, Paul. “Les Empereurs Romains Initiés Aux Mystères d’Éleusis.” Comptes Rendus Des Séances de l’Académie Des Inscriptions et Belles-Lettres 36, no. 6 (1892): 384. doi:10.3406/crai.1892.70193.",
  "Geagan, Daniel. “Hadrian and the Athenian Dionysiac Technitai.” Transactions and Proceedings of the American Philological Association 103 (1972): 133-160.",
  "Graindor, Paul. Athènes de Tibère à Trajan. Cairo: Imprimerie Nationale, 1931.",
  "Graindor, Paul. Athènes Sous Hadrien. Cairo: Imprimerie Nationale, 1934.",
  "Jordan, D.R. \"Defixiones from a Well Near the Southwest Corner of the Athenian Agora.\" Hesperia 54, no. 3 (1985): 205-55.",
  "Karo, George. An Attic Cemetery: Excavations in the Kerameikos at Athens under Gustav Oberlaender and the Oberlaender Trust. Philadelphia: The Obverlaender Trust, 1943.",
  "Longfellow, Brenda. \"Roman Fountains in Greek Sanctuaries.\" American Journal of Archaeology 116, 1 (January 2012): 133-55.",
  "Oliver, James H. “Three Attic Inscriptions Concerning the Emperor Commodus.” The American Journal of Philology 71, no. 2 (January 1, 1950): 170–179.",
  "Oliver, J. \"The Sacred Gerusia and the Emperor's Consilium.\" Hesperia 36, no. 3 (1967): 329-335.",
  "Oliver, J. Marcus Aurelius: Aspects of Civic and Cultural Policy in the East. Hesperia Supplements 13. Princeton, NJ: The American School of Classical Studies at Athens, 1970.",
  "Oliver, James H. \"Hadrian's Reform of the Appeal Procedure in Greece.\" Hesperia 39, no. 4 (1970): 332-6.",
  "Oliver, J. \"Greek Applications for Roman Trials.\" The American Journal of Philology 100, no. 4 (1979): 542-58.",
  "Oliver, James H. \"Roman Emperors and Athens.\" Historia: Zeitschrift für Alte Geschichte 30, no. 4 (1981): 412-23.",
  "Oliver, J. Greek Constitutions of Early Roman Emperors from Inscriptions and Papyri. Philadelphia: American Philosophical Society, 1989.",
  "Owens, E. J. “Increasing Roman Domination of Greece in the Years 48-27 B.C.” Latomus 35, no. 4 (October 1, 1976): 718–729.",
  "Pek, Bemardine. “The Sanctuary of Demeter and Kore at Eleusis in the Roman World.” M.A. Thesis, McMaster University, 1998. http://digitalcommons.mcmaster.ca/opendissertations/6402.",
  "Raubitschek, A. E. “Commodus and Athens.” Hesperia Supplements 8 (January 1, 1949): 279–466.",
  "Riccardi, Lee Ann. \"The Bust-Crown, The Panhellenion, and Eleusis: A New Portrait from the Athenian Agora.\" Hesperia 76, no. 2 (2007): 365-90.",
  "Rizzi, Marco. Hadrian and the Christians. Millennium Studies 30. Berlin: De Gruyter, 2010.",
  "Romeo, Ilaria. \"The Panhellenion and Ethnic Identity in Hadrianic Greece.\" Classical Philology 97 (2002): 21-40.",
  "Spawforth A.J. and S. Walter. “The World of the Panhellenion. I. Athens and Eleusis.” The Journal for Roman Studies 75 (1985): 78-104.",
  "Spawforth A.J. and S. Walter. \"The World of the Panhellenion, II. Three Dorian Cities.\" Journal for Roman Studies 76 (1986): 88-105.",
  "Vout, Caroline. \"Hadrian, Hellenism, and the Social History of Art.\" Arion 18, no. 1 (2010): 55-78.",
  "Walker, Susan, and Avril Cameron, eds. The Greek Renaissance in the Roman Empire: Papers from the Tenth British Museum Colloquium. Bulletin of the Institute of Classical Studies of the University of London Supplement 55. London: University of London Institute of Classical Studies, 1989.",
  "Williams, Ellen Reader. \"Isis Pelagia and a Roman Marble Matrix from the Athenian Agora.\" Hesperia 54, no. 2 (1985): 109-19.",
  "Williams, W. \"Formal and Historical Aspects of Two New Documents of Marcus Aurelius.\" Zeitschrift für Papyrologie und Epigrafik 17 (1975): 37-78.",
  "Wiseman, T.P. “Pulcher Claudius.” Harvard Studies in Classical Philology 74 (January 1, 1970): 207–221.",
  "Ajootian, Aileen. \"A Roman Athena from the Pnyx and the Agora in Athens.\" Hesperia 78, no. 4 (2009): 481-99.",
  "Armstrong, Joe E and John McK. Camp II. \"Notes on a Water Clock in the Athenian Agora.\" Hesperia 46, no. 2 (1977): 147-61.",
  "Camp, John M.  The Athenian Agora: Excavations in the Heart of Classical Athens. New Aspects of Antiquity. London: Thames and Hudson, 1970.",
  "Caskey, Lacey D. “Notes on Inscriptions from Eleusis Dealing with the Building of the Porch of Philon.” American Journal of Archaeology 9, no. 2 (April 1, 1905): 147–156.",
  "Culley, Gerald R. \"The Restoration of Sanctuaries in Attica I.G. II2, 1035.\" Hesperia 44, no. 2 (1975): 207-23.",
  "Davis, Philip H. “The Foundations of the Philonian Portico at Eleusis.” American Journal of Archaeology 34, no. 1 (January 1, 1930): 1–19.",
  "Dinsmoor, W.B. Jr \"The Monopteros in the Athenian Agora.\" Hesperia 43, 4 (1974): 412-27.",
  "Edwards, G. Roger. \"Panathenaics of Hellenistic and Roman Times.\" Hesperia 26, no. 4: (1943).",
  "Fowden, Garth. \"City and Mountain in Late Roman Attica.\" Journal of Hellenic Studies 108 (1988): 48-59.",
  "Frantz, Alison. \"A Public Building of Late Antiquity in Athens (IGII2 5205)\" Hesperia 48, no. 2 (1979):194-203.",
  "Kroll, John H. \"The Eleusis Hoard of Athenian Imperial Coins and Some Deposits from the Athenian Agora.\" Hesperia 42, no. 3 (1973): 321-33.",
  "Krumeich, Ralf and Christian Witschel, eds. Die Akropolis von Athen im Hellenismus und in der römischen Kaiserzeit. Wiesbaden: Reichert, 2010.",
  "Miller, Stephen G. “Addendum to ‘A Roman Monument in the Athenian Agora.’” Hesperia 41, no. 4 (October 1, 1972): 475–476.",
  "Schmalz, Geoffrey C. R. \"Athenian Prytaneion Discovered?\" Hesperia 75 (2006): 33-81.",
  "Shear, T. Leslie Jr. “The Monument of the Eponymous Heroes in the Athenian Agora.” Hesperia 39, no. 3 (1970): 145-222.",
  "Simon, Erika. Festivals of Attica, an Archaeological Commentary. Madison: University of Wisconsin Press, 1983.",
  "Society of Dilettanti. The Unedited Antiquities of Attica: Comprising the Archaeological Remains of Eleusis, Rhamnus, Sunium, and Thoricus. London. 1817.",
  "Sturgeon, Mary C. \"The Reliefs of the Theater of Dionysos in Athens.\" American Journal of Archaeology  81, no. 1 (1977): 31-53.",
  "Theocharaki, Anna Maria. \"The Ancient Circuit Wall of Athens.\" Hesperia 80, no. 1 (2011): 71-156.",
  "Travlos, John. \"The Topography of Eleusis.\" Hesperia 18, no. 1 (1949): 138-47.",
  "Vanderpool, Eugene. \"The 'Agora' of Pausanius I, 17, 1-2.\" Hesperia 43, no. 3 (1972): 308-10.",
  "Walker, Susan. “A Sanctuary of Isis on the South Slope of the Athenian Acropolis.” The Annual of the British School at Athens 74 (January 1, 1979): 243–258.",
  "Anderson, Graham. The Second Sophistic: A Cultural Phenomenon in the Roman Empire. London: Routledge, 1993.",
  "Borg, Barbara, ed. Paideia: The World of the Second Sophistic. Millenium Studies 2. Berlin: Walter de Gruyter, 2004.Bowersock, G.W. Greek Sophists in the Roman Empire. Oxford: Oxford University Press, 1969.",
  "Bowersock, G.W., ed. Approaches to the Second Sophistic: Papers presented at the 105th Annual Meeting of the American Philological Association. Philadelphia: American Philological Association, 1974.",
  "Bowie, E.L. \"The Greeks and their Past in the Second Sophistic.\" Past and Present 46 (1970): 3-41.",
  "Garnsey, Peter, Dominic Rathbone, and Alan K. Bowman, eds. The High Empire A.D. 70-192. Vol. 11 in The Cambridge Ancient History, 2nd ed. Cambridge: Cambridge University Press, 2000.",
  "Geiger, Joseph. \"Notes on the Second Sophistic in Palestine.\" Illinois Classical Studies 19 (1994): 221-30.",
  "Gleason, Maud W. Making Men: Sophists and Self-Presentation in Ancient Rome. Princeton, NJ: Princeton University Press, 1995.",
  "Goldhill, Simon, ed. Being Greek Under Rome: Cultural Identity, the Second Sophistic and the Development of Empire. Cambridge: Cambridge University Press, 2001.",
  "Haase, Wolfgang, ed. Sprache und Literatur (einzelne Autoren seit der hadrianischen Zeit und Allgemeines zur Literatur des 2. und 3. Jahrhunderts, 4 Vols. Aufstieg und Niedergang der römischen Welt 34. Berlin: Walter de Gruyter, 1993-8.",
  "Kapetanopoulos, Elias. \"Salamis and Julius Nikanor.\" Hellenica 33 (1981): 217-37.",
  "Kapetanopoulos, Elias. \"Gaius Julius Nikanor, Neos Homeros kai Neos Themistokles.\" Rivista di filologia e di istruzione classica 104 (1976): 375-7.",
  "Kapetanopoulos, Elias. \"Arrian's Praenomen Again.\" Ἀρχαιολογικὰ Ἀνάλεκτα ἐξ Ἀθηνῶν 6 (1973): 301-4.",
  "Kerferd, G.B. The Sophistic Movement. Cambridge: Cambridge University Press, 1981.",
  "Nagy, Gregory. Greek Literature in the Byzantine Period. Greek Literature 9. London: Routledge, 2001.",
  "Nasrallah, Laura. \"Mapping the World: Justin, Tatian, Lucian, and the Second Sophistic.\" Harvard Theological Review 98, no. 3 (2005): 283-314.",
  "Ostenfeld, Eric. Greek Romans and Roman Greeks. Studies in Cultural Interaction. Aarhus: Aarhus University Press, 2002.",
  "Penella, Robert J. Canons of Style in the Antonine Age: Idea-Theory and its Literary Context. Oxford: Oxford University Press, 1999.",
  "Puech, Bernadette. Orateurs et sophistes grecs dans les inscriptions d’époque impériale. Paris: Libraire Philosophique J. Vrin, 2002.",
  "Raubitschek, A. E. “Phaidros and His Roman Pupils.” Hesperia: The Journal of the American School of Classical Studies at Athens 18, no. 1 (January 1, 1949): 96–103.",
  "Schmidt, Thomas, and Pascale Fleury. Perceptions of the Second Sophistic and its Times. Phoenix Supplementary Volumes. Toronto: University of Toronto Press, 2011.",
  "Schmitz, T. Bildung und Macht. Zur sozialen und politischen Funktion der zweiten Sophistik in der griechischen Welt der Kaiserzeit. Munich: C.H. Beck, 1997.",
  "Swain, Simon. Hellenism and Empire. Language, Classicism and Power in the Greek World, AD 50-250. Clarendon Paperbacks. Oxford: Oxford University Press, 1996.",
  "Van Hoof, Lieve. \"Performing Paideia: Greek Culture as an Instrument for Social Promotion in the Fourth Century A.D.\" The Classical Quarterly 61, no. 1 (2013): 387-406.",
  "Whitmarsh, Tim. The Second Sophistic. Greece and Rome - New Surveys in the Classics 35. Oxford: Oxford University Press, 2005.",
  "Whitmarsh, Time. Greek Literature and the Roman Empire. The Politics of Imitation. Oxford: Oxford University Press, 2001 Oxford.",
  "Avi-Yonah, Michael. Abbreviations in Greek Inscriptions (The Near East, 200 B.C. - A.D. 1100). Quarterly of the Department of Antiquities in Palestine Suppl. to vol. 9. London: Oxford University Press, 1940.",
  "Mason, Hugh. Greek Terms for Roman Institutions: A Lexicon and Analysis. Toronto: Hakkert, 1974.",
  "McClean, Bradley, H. An Introduction to Greek Epigraphy of the Hellenistic and Roman Periods from Alexander the Great down to the Reign of Constantine. Ann Arbor: University of Michigan Press, 2011.",
  "Bodel, John, ed. Epigraphic Evidence: Ancient History from Inscriptions. Routledge: London, 2001.",
  "Chatzes, A. \"Αττικὴ ἐπιγραφὴ ἀεισίτων.\" Archaiologike Ephemeris (1925/6): 94-7.",
  "Daly, Kevin F. \"A New Athenian Ephebic List: Agora I 7545.\" Hesperia 78, no. 3 (2009): 405-19.",
  "Dow, Sterling. “Prytaneis: A Study of the Inscriptions Honoring the Athenian Councillors.” Hesperia Supplements 1 (January 1, 1937): 1–258.",
  "Follet, S. and D. Peppas-Delmousou. \"Les dedicaces chorégiques d'époque flavienne et antonine à Athènes.\" In The Greek East in the Roman Context. Edited by Olli Salomies, 95-117. Helsinki: Finnish Institute at Athens, 2001.",
  "Hagemajer-Allen, Katarzyna. \"Intercultural Exchanges in Fourth-Century Attica Decrees.\" Classical Antiquity 22, no. 2 (2003): 199-246.",
  "Hedrick, Charles W. Jr. \"Democracy and the Athenian Epigraphical Habit.\" Hesperia 68, no. 3 (1999): 387-439.",
  "Henry, A.S. Honours and Privileges in Athenian Decrees. Subsidia Epigraphica. Hildesheim: Georg Olms, 1983.",
  "Henry, A.S. The Prescripts of Athenian Decrees. Mnemosyne Supplement 49. Leiden: Brill, 1977.",
  "Henry, Alan S. “The Athenian State Secretariat and Provisions for Publishing and Erecting Decrees.” Hesperia 71, no. 1 (January 1, 2002): 91–118.",
  "Kapetanopoulos, Elias. \" Ἐφηβικὸς Κατάλογος Ἀναχρονολογουμενός.\" Ἀρχαιολογικὰ Ἀνάλεκτα ἐξ Ἀθηνῶν 7 (1974): 96-8.",
  "Lambert, Stephen. \"Athenian State Laws and Decrees, 352/1-322/1: I Decrees Honouring Athenians.\" ZPE 150 (2004): 85-120.",
  "Lambert, Stephen. \"Athenian State Laws and Decrees, 352/1-322/1: II Religious Regulations.\" ZPE 154 (2005): 125-59.",
  "Lambert, Stephen. \"Athenian State Laws and Decrees, 352/1-322/1: III Decrees Honouring Foreigners A. Citizenship, Proxeny and Euergesy.\" ZPE 158 (2006): 115-58.",
  "Meyer, E.A. \"Explaining the Epigraphic Habit in the Roman Empire: The Evidence of Epitaphs.\" The Journal of Roman Studies 80 (1990): 74-96.",
  "Meyer, E.A. \"Epitaphs and Citizenship in Classical Athens.\" The Journal of Hellenic Studies 113 (1993): 99-121.",
  "Mitsos, M. \"Ἀπὸ τοὺς καταλόγους Ἀθηναίων Ἐφήβων κ.λ.π. Ι.\" Archaiologikon Deltion 25 (1970): 184-90.",
  "Mitsos, M. \"Ἀπὸ τοὺς καταλόγους Ἀθηναίων Ἐφήβων κ.λ.π. ΙI.\" Archaiologike Ephemeris (1970): 114-24.",
  "Mitsos, M. \"Ἀπὸ τοὺς καταλόγους Ἀθηναίων Ἐφήβων κ.λ.π. ΙII.\" Archaiologike Ephemeris (1971): 56-65.",
  "Mitsos, M. \"Ἀπὸ τοὺς καταλόγους Ἀθηναίων Ἐφήβων κ.λ.π. ΙV.\" Archaiologike Ephemeris (1972): 55-69.",
  "Mitsos, M. \"Ἀπὸ τοὺς καταλόγους Ἀθηναίων Ἐφήβων κ.λ.π. VII.\" Archaiologike Ephemeris (1973): 87-92.",
  "Mitsos, M. \"Some Lists of Athenian Ephebes: VI\" In ΦΟΡΟΣ: A Tribute to Benjamin D. Meritt. Edited by Donald William Bradeen and and Malcom Francis MacGregor, 117-20. Locus Valley, NY: J.J. Augustin, 1974.",
  "Mitsos, M. \"Ἀπὸ τοὺς καταλόγους Ἀθηναίων Ἐφήβων κ.λ.π. VIII.\" Archaiologike Ephemeris (1977): 12-22.",
  "Notopoulos, James A. “Notes on Athenian Inscriptions of the Empire Period.” The American Journal of Philology 69, no. 4 (January 1, 1948): 415–419.",
  "Osborne, Robin. \"The Politics of an Epigraphic Habit.\" In Greek History and Epigraphy. Essays in Honor of P.J. Rhodes., edited by Lynette Mitchell and Lene Rubinstein. Swansea: The Classical Press of Wales, 2009.",
  "Rhodes, P. J. “State and Religion in Athenian Inscriptions.” Greece & Rome 56, no. 1 (April 1, 2009): 1–13.",
  "Tracy, Stephen and Constantin Papaodysseus. \"The Study of Ηands on Greek Inscriptions: The Need for a Digital Approach.\" American Journal of Archaeology 113, no. 1 (January 2009): 99-102.",
  "Traill, John S. \"Greek Inscriptions Honoring Prytaneis.\" Hesperia 40, no. 3 (1971): 308-29.",
  "Traill, John S. \"Prytany and Ephebic Inscriptions from the Athenian Agora.\" Hesperia 51, no. 2 (1982): 197-235.",
  "Woloch, Michael. “Roman and Athenian Citizenship at Athens A.D. 96-161.” Historia: Zeitschrift für Alte Geschichte 20, no. 5/6 (December 1, 1971): 743–750.",
  "Barnish, S.J.B. \"A Review of the Prosopography of the Later Roman Empire.\" Journal of Roman Studies 84 (1994): 171-7.",
  "Broughton, T. Robert. The Magistrates of the Roman Republic. Ann Arbor: University of Michigan Press, 1952.",
  "Develin, Robert. Athenian Officials: 684-321BC. Cambridge: Cambridge University Press, 1989.",
  "Davies, J.K. Athenian Propertied Families. Oxford: Oxford University Press, 1971.",
  "Gelzer, Matthias. Die Nobilität der römischen Republik. Reprint. Teubner: Stuttgart, 1983.",
  "Jones, A.H.M., J.R. Martindale, and John Morris, eds. Prosopography of the Later Roman Empire, 3 Vols. Cambridge: Cambridge University Press, 1971-92.",
  "Salomies, O. Die römische Vornamen. Studien zur römische Namengebung. Ekenäs: Societas Scientiarum Fennica, 1987.",
  "Solin, Heikki. Die Stadtromischen Sklavennamen: Ein Namenbuch, 3 vols. Forschungen zur antiken Sklaverei, Supplement 2. Stuttgart: Franz Steiner Verlag, 1996.",
  "Baslez, M-F. \"Citoyens et non-citoyens dans l'Athènes imperiale au Ier et au IIe siècle de notre ère.\" Bulletin of the Institute of Classical Studies of the University of London Supplement 55 (1989): 17-36.",
  "Bayliss, Andrew J. “New Names on an Athenian Ephebic Inscription.” Zeitschrift für Papyrologie und Epigraphik 140 (January 1, 2002): 85–88.",
  "Byrne, Sean. “‘IG’ II2 1095 and the Delia of 98/97 BC. A Document about the Athenian Politician Medeios.” Zeitschrift für Papyrologie und Epigraphik 109 (January 1, 1995): 55–61.",
  "Clinton, Kevin. \"Publius Papinius St[---] at Eleusis.\" Transactions and Proceedings of the American Philological Association 103 (1972): 79-82.",
  "Daly, Kevin F. \"Two Inscriptions from the Athenian Agora: I 7571 and I 7579.\" Hesperia 76, no. 3 (2007): 539-54.",
  "Dow, S. \"The Purported Decree of Themistokles: Stele and Inscription.\" American Journal of Archaeology 66 (1962): 353-68.",
  "Geagan, Daniel. “Greek Inscriptions from the Athenian Agora.” Hesperia 52, no. 2 (1983): 155-172.",
  "Graindor, Paul. “Inscriptions attiques d'époque impériale. Textes inédits et corrections” Bulletin de Correspondance Hellénique 38 (1914): 351-443.",
  "Graindor, Paul. Album d'inscriptions attiques d'époque impériale. Paris: Champion, 1924.",
  "Graindor, Paul. \"Inscriptions attiques d'époque romaine.\" Bulletin de Correspondance Hellenique 51 (1927): 245-328.",
  "Jones, C.P. \"Three Foreigners in Attica.\" Phoenix 32, no.3 (1978): 222-234.",
  "Jones, C.P. \"An Athenian Document Mentioning Julias Nicanor.\" Zeitschrift für Papyrologie und Epigrafik 154 (2005): 161-72.",
  "Kapetanopoulos, Elias. \"Εἰς Ἀττικὰς ἐφηβικὰς ἐπιγραφάς: IG ii2 2235.\" in ΦΙΛΙΑ ΕΠΗ εἰς Γεώργιον Ε. Μυλώναν, Vol. III: 261-70. Athens, 1986.",
  "Kapetanopoulos, Elias. \" Ο Φούριος Μάρκελλος (Α´) Γαργήττιος.\" Athena 76 (1977)\" 182-6.",
  "Kapetanopoulos, Elias. \" Ἐπιγραφαὶ ἐξ Ἐλευσῖνος.\" Archaiologike Ephemeris (1981): 23-36.",
  "Kapetanopoulos, Elias. \"Flavius Onesikrates and Fellow Ephebes.\" Talanta 6 (1974): 24-9.",
  "Kapetanopoulos, Elias. \" Κλαύδιος Δημόστρατος καὶ Αὐρήλιος Εὐκαρπίδης.\" Archaiologike Ephemeris Chron (1974): 3-4.",
  "Kapetanopoulos, Elias. \"The Family of Dexippos I Hermeios.\" Archaiologike Ephemeris (1972): 133-72.",
  "Kapetanopoulos, Elias. \"A Phalerian Family and its Relations.\" Archaiologikon Deltion 26 (1971): 277-316.",
  "Kapetanopoulos, Elias. \" Ἀναθηματικὴ ἐπιγραφὴ ἐξ Ἐλευσῖνος.\" Archaiologike Ephemeris (1964): 120-3.",
  "Ma, John and Stephen V. Tracy. \"Notes on Attic Statue Bases.\" Zeitschrift für Papyrologie und Epigrafik 150 (2004). 121-6.",
  "Meisterhans, K. Grammatik der Attischen Inschriften, dritte vermehte und verbesserte Auflage besorgt von E. Schwyzer. Berlin, 1900.",
  "Meritt, Benjamin. D. “Greek Inscriptions.” Hesperia 8, no. 1 (1939): 48-82.",
  "Meritt, Benjamin .D. “Greek Inscriptions.” Hesperia 9, no. 1 (1940): 53-96.",
  "Meritt, Benjamin D., A.G. Woodhead, and G. Stamires. “Greek Inscriptions.” Hesperia 26, no. 3 (1957): 198-270.",
  "Meritt, Benjamin D. \"The Hadrianic Year of the Council at Athens.\" Hesperia 43, no. 4 (1974): 460-6.",
  "Oliver, James H. “The ΜΟϒΣΕΙΟΝ in Late Attic Inscriptions.” Hesperia 3, no. 2 (January 1, 1934): 191–196.",
  "Raubitschek, A.E. “The New Homer.” Hesperia 23, no. 4 (1954): 317-9.",
  "Reinmuth, O. W. “The Attic Archons Named Apolexis.” Bulletin de Correspondance Hellénique 90, no. 1 (1966): 93–100.",
  "Reinmuth, O. W. “A New Ephebic Inscription from the Athenian Agora.” Hesperia 43, no. 2 (April 1, 1974): 246–259.",
  "Robert, Louis. “Deux Inscriptions De L’epoque Imperiale En Attique.” The American Journal of Philology 100, no. 1 (April 1, 1979): 153–165.",
  "Traill, John S. “Greek Inscriptions from the Athenian Agora: Addenda to the Athenian Agora, Vol. XV, Inscriptions: The Athenian Councillors.” Hesperia 47, no. 3 (July 1, 1978): 269–331.",
  "Threatte, L. The Grammar of Attic Inscriptions, 2 vols. Berlin: Walter de Gruyter, 1980-96.",
  "Barnes, J.A. \"Networks and political processes.\" In Social Networks in Urban Situations: Analyses of Personal Relationships in Central African Towns, edited by James Clyde Mitchell, 51-75. Manchester: Manchester University Press, 1969.",
  "Bearman, Peter, James Moody, and Katherine Stovel. \"Chains of Affection: The Structure of Adolescent Romantic and Sexual Networks\" American Journal of Sociology 110 (2004): 44-91.",
  "Berardo, Ramiro. \"Networking Networkers: An Initial Exploration of the Patterns of Collaboration among the Members of a New Community in Political Science.\" Political Science and Politics 44, no. 1 (2011): 69-75.",
  "Erickson, Bonnie H. \"Social Networks and History: A Review Essay.\" Historical Methods 30 (1997): 149-57.",
  "Eulau, Heinz. \"The Columbia Studies of Personal Influence: Social Network Analysis.\" Social Science History 4 no. 2 (1980): 207-228.",
  "Fararo, T.JH. and M. Sunshine. A Study of a Biased Friendship Net. Syracuse: Syracuse University, 1964.",
  "Franzosi, Roberto. \"A Sociologist meets History. Critical Reflections upon Practice.\" Journal of Historical Sociology 9 (1996): 354-92.",
  "Franzosi, Roberto, and John W. Mohr. \"New Directions in Formalization and Historical Analysis.\" Theory and Society 26 (1997): 133-60.",
  "Lazer, David. \"Networks in Political Science: Back to the Future.\" Political Science and Politics 44, no. 1 (2011): 61-68.",
  "Meadows, R.D. \"Engineering Exile: Social Networks and the French Atlantic Community, 1789-1809\" French Historical Studies 23. no. 1 (2000): 67-102.",
  "Sokhey, Anand E. and Paul A. Djupe. \"Interpersonal Networks and Democratic Politics.\" Political Science and Politics 44, no. 1 (2011): 55-59.",
  "Wetherell, C., A. Plakans, and Barry Wellman. \"Social Networks, Kinship, and Community in Eastern Europe.\" Journal of Interdisciplinary History 24, no. 4 (1994): 639-663.",
  "Alexander, M., and J.A. Danowski. \"Analysis of an ancient network.\" Social Networks 12 (1990): 313-35.",
  "Chow, John K. Patronage and Power: A Study of Social Networks in Corinth. Journal for the Study of the New Testament Supplement. Sheffield: Sheffield Academic Press, 1992.",
  "Clark, Elizabeth A. \"Elite networks and heresy accusations: towards a social description of the Origenist controversy.\" Semeia 56 (1992): 81-107.",
  "Coward, Fiona. \"Small Worlds, Material Culture and Ancient Near Eastern Social Networks.\" In Social Brain, Distributed Mind, edited by Robin Dunbar, Clive Gamble, and John Gowlett. Oxford: Oxford University Press, 2010.",
  "Goudriaan, Koen, et al., eds. Prosopography and Computer Leuven, Belgium: Garant, 1995.",
  "Graham, Shawn. \"Who's in Charge? Studying Social Networks in the Roman Brick Industry in Central Italy.\" in Acta of the XVIth International Congress of Classical Archaeology, Edited by C. Mattusch and A. Donohue, . Boston: Oxbow, 2003.",
  "Graham, Shawn. Ex Figlinis: The Network Dynamics of the Tiber Valley Brick Industry in the Hinterland of Rome. Oxford: British Archaeology Reports, 2006.",
  "Graham, Shawn. \"Behavior Space: Simulating Roman Social Life and Civil Violence.\" Digital Studies 1, no. 2 (2009). http://www.digitalstudies.org/ojs/index.php/digital_studies/article/view/172",
  "Graham, Shawn. \"Networks, agent-based models and the Antonine itineraries: implications for Roman archaeology.\" The Journal of Mediterranean Archaeology 19, no. 1 (2006): 45-64.",
  "Graham, Shawn, and G. Ruffini. \"Network Analysis and Greco-Roman Prosopography.\" in Prosopography Approaches and Applications. A Handbook, edited by K.S.B. Keats-Rohan, 325-36. Oxford: Occasional Publications of the Unit for Prosopographical Research, Linacre College, 2007.",
  "Graham, Shawn, S. Weingart, I. Milligan. \"Getting started with Topic Modeling.\" The Programming Historian 2, edited by William Turkel and Adam Crymble. http://programminghistorian.org/",
  "Graham, Shawn and J. Steiner. “Travellersim: Growing Settlement Structures and Territories with Agent-Based Modeling.” In Digital Discovery: Exploring New Frontiers in Human Heritage. CAA 2006. Computer Applications and Quantitative Methods in Archaeology. Proceedings of the 34th Conference, Fargo, United States, April 2006, edited by Jeffrey T. Clark and Emily M. Hagemeister, 57-70. Budapest: Archaeolingua, 2007.",
  "Horden, Peregrine, and Nicholas Purcell. The Corrupting Sea: A Study of Mediterranean History. Oxford: Wiley-Blackwell, 2000.",
  "Knappett, Carl. An Archaeology of Interaction: Network Perspectives on Material Culture and Society. Oxford: Oxford University Press, 2011.",
  "Malkin, Irad, Christy Constantakopoulou, and Katerina Panagopoulou, eds. Greek and Roman Networks in the Mediterranean. London: Routledge, 2009.",
  "Malkin, Irad. A Small Greek World: Networks in the Ancient Mediterranean. Oxford: Oxford University Press, 2011.",
  "McCormick, Michael. Origins of the European Economy: Communications and Commerce AD 300-900. Cambridge: Cambridge University Press, 2002.",
  "Ruffini, Giovanni. Social Networks in Byzantine Egypt. Cambridge: Cambridge University Press, 2008.",
  "Adhikari, A., L. Denby, J.M. Landwehr, and J. Meloche. \"Using Data Network Metics, Graphics, and Topology to Explore Network Characteristics.\" Lecture Notes-Monograph Series 54 (2007): 62-75.",
  "Bastian M., Heymann S., Jacomy M. \"Gephi: An Open Source Software for Exploring and Manipulating Networks.\" International AAAI Conference on Weblogs and Social Media (2009): http://www.aaai.org/ocs/index.php/ICWSM/09/paper/view/154",
  "Borgatti, S.P., M.G. Everett, and L.C. Freeman. Ucinet for Windows: Software for Social Network Analysis. Cambridge, MA: Harvard Analytic Technologies, 2002.",
  "Cao, J., Davis D., Vander Wiel S., and Yu, B. \"Time-varying Network Tomography: Router Link Data. Journal of the American Statistical Association 95 (2000): 1063-75.",
  "Castro, Rui, Mark Coates, Gang Liang, Robert Nowak, and Bin Yu. \"Network Tomography: Recent Developments.\" Statistical Science 19, no. 3 (2004): 499-517.",
  "Freeman, Linton, and C.R. Thompson. \"Estimating Acquaintanceship Volume.\" In The Small World, Edited by M. Kochen, 147-58. Norwood, NJ: Ablex Publishing, 1989.",
  "Freeman, Linton. \"Visualizing Social Networks.\" Journal of Social Structure 1 (2000). http://www.cmu.edu/joss/index.html",
  "Rhodes, C.J., and E.M.J. Keefe. \"Social Network Topology: A Bayesian Approach.\" Journal of the Operational Research Society 58 (2007): 1605-11.",
  "Vardi, Y. \"Network Tomography: Estimating Source-Destination Traffic Intensities from Link Data.\" Journal of the American Statistical Association 91 (1996): 365-377.",
  "Vardi, Y. \"Metrics Useful in Network Tomography Studies.\" IEEE Signal Processing Letters 11 (2004): 353-55.",
  "Anderson, Greg. \"The Personality of the Greek State.\" Journal of Hellenic Studies 129 (2009): 1-22.",
  "Anderson, Greg. The Athenian Experiment: Building an Imagined Political Community in Ancient Attica, 508-490 BC. Ann Arbor: University of Michigan Press, 2003.",
  "Chaniotis, Angelos. Die Verträge zwischen kretischen Poleis in der hellenistischen Zeit. Heidelberger althistorische Beiträge und epigraphische Studien 24. Stuttgart: Franz Steiner Verlag, 1996.",
  "Dmitriev, Sviatoslav. City Government in Hellenistic and Roman Asia Minor. Oxford: Oxford University Press, 2005.",
  "Evans, J.A.S., ed. Polis and Imperium: Studies in Honor of Edward Togo Salmon. Toronto: Edgar Kent, 1974.",
  "Grieb. Volker. Hellenistische Demokratie: politische Organisation und Struktur in freien griechischen Poleis nach Alexander dem Grossen. Historia Einzelschriften 199. Stuttgart: Franz Steiner Verlag, 2008.",
  "Habermas, Jürgen. Strukturwandel der Öffentlichkeit. Untersuchungen zu einer Kategorie der bürgerlichen Gesellschaft. Stuttgart: Franz Steiner Verlag: 1962.",
  "Ma, John. \"Peer Polity Interaction in the Hellenistic Age.\" Past & Present 180 (2003): 9-39.",
  "Ma, John. \"Fighting Poleis of the Hellenistic World.\" In War and Violence in Ancient Greece, edited by Hans van Wees, 227-276. London: Duckworth, 2000.",
  "Martzavou, Paraskevi and Nikolaos Papazarkadas, eds. Epigraphical Approaches to the Post-classical Polis: Fourth Century BC to Second Century AD. Oxford: Oxford University Press, 2013.",
  "Vlassopoulos, Kostas. Unthinking the Greek Polis. Ancient Greek History Beyond Eurocentrism. Cambridge: Cambridge University Press, 2007.",
  "Wörrle, M. and Zanker, P., eds. Stadtbild und Bürgerbild im Hellenismus: Kolloquium, München, 24. bis 26, Uni 1993. Munich: C.H. Beck, 1995.",
  "Bielfeldt, Ruth. \"Polis Made Manifest. The Physiognomy of the Public in the Hellenistic City - with a Case study of the Agora in Priene.\" In Politische Kommunikation und öffentliche Meinung in der antiken Welt., edited by Ch. Kuhn, 78-122. Stuttgart: Franz Steiner Verlag, 2012.",
  "Coulton, J.J. \"Opramoas and the Anonymous Benefactor.\" Journal of Hellenic Studies 107 (1987): 171-8.",
  "Dillion, Sheila and Elizabeth Palmer Baltes. \"Honorific Practices and the Politics of Space on Hellenistic Delos: Portrait Statue Monuments Along the Dromos.\" American Journal of Archaeology 117, no. 2 (2013): 207-46.",
  "Fröhlich, P. Les Cités grecques et le contrôle des magistrats (IVe-Ier siècle avant J.-C.). Hautes Études du monde gréco-romain 33. Geneva: Droz, 2004.",
  "Fröhlich P., and Christel Müller, eds. Citoyenneté et participation à la basse époque hellénistique. Hautes Études du monde gréco-romain 35. Geneva: Droz, 2005.",
  "Geagan, Daniel. \"The Sarapion Monument and the Quest for Status in Roman Athens.\" ZPE 85 (1991): 145-65.e",
  "Graham, Abigail S. \"The Word is Not Enough: A New Approach to Assessing Monumental Inscriptions. A Case Study from Roman Ephesos.\" American Journal of Archaeology 117, no. 3 (July 2013): 383-412.",
  "Heberday, Rudolf. Opramoas: Inschriften vom Heroon zu Rhodiapolis. Wien, 1897.",
  "Kapetanopoulos, Elias. \"The Sarapion Monument at Athens.\" Prometheus 20 (1994): 234-242.",
  "Kokkinia, Christina. Die Opramoas-Inschrift von Rhodiapolis. Euergetismus und soziale Elite in Lykien. Antiquitas Series 3, Vol. 40. Bonn: Dr. Rudolf Habelt GMBH, 2000.",
  "Klaffenbach, G., 1957. Griechische Epigraphik. Göttingen.",
  "Klaffenbach, G. \"Bemerkungen zum griechischen Urkundenwesen\". Sitzungsberichte der deutschen Akademie der Wissenschaften zu Berlin 6 (1960): 5-41.",
  "Ma, John. \" Hellenistic Honorific Statues and their Inscriptions.\" In Art and Inscriptions in the Ancient World, edited by Zahra Newby and Ruth Leader-Newby, 203-20. Cambridge: Cambridge University Press, 2007.",
  "Ma, John. \"Observations on Honorific Statues at Oropos (and Elsewhere).\" ZPE 160 (2007): 89-96.",
  "Ma, John. Statues and Cities: Honorific Portraits and Civic Identity in the Hellenistic World. Oxford: Oxford University Press, 2013.",
  "Oliver, Graham J. \"Space and the Visualization of Power in the Greek Polis: The Award of Statues in Decrees from Athens.\" in Early Hellenistic Portraiture: Image, Style, Context. Edited by R. von den Hoff and P. Schultz. Cambridge: Cambridge University Press, 2007.",
  "Oliver, Graham J. \"Citizenship: Inscribed Honors for Individuals in Classical and Hellenistic Athens.\" In Individus, groupes, et politique à Athènes de Solon a Mithridate. Edited by J-Chr. Couvenhes and S. Milanezi. Presses Universitaires Francois Rabelais, 2007.",
  "Oliver, J. \"The Sarapion Monument and the Paean of Sophocles.\" Hesperia 5 (1936): 91-122.",
  "Shear, Julia L. \"Reusing Statues, Rewriting Inscriptions and Bestowing Honours in Roman Athens.\" In Art and Inscriptions in the Ancient World, edited by Zahra Newby and Ruth Leader-Newby, 221-46. Cambridge: Cambridge University Press, 2007.",
  "Smith, R.R.R. \"Cultural Choice and Political Identity in Honorific Portrait Statues in the Greek East in the Second Century A.D.\" The Journal for Roman Studies 88 (1998): 56-93.",
  "Wilhelm, A. Beiträge zur Griechischen Inschriftenkunde. Vienna, 1909.",
  "Zuiderhoek, Arjan. The Politics of Munificence in the Roman Empire. Citizens, Elites, and Benefactors in Asia Minor. Greek Culture in the Roman World. Cambridge: Cambridge University Press, 2009.",
  "Clinton, Kevin. “A Family of Eumolpidai and Kerykes Descended from Pericles.” Hesperia 73,  no. 1 (2004): 39-57.",
  "Horster, Marietta. \"Lysimache and the Others: Some Notes on the Position of Women in Athenian Religion.\" in Studies in Greek Epigraphy and History in Honor of Stephen V. Tracy. Études Ausonius Institute 26. Edited by Gary Reger, F.X. Ryan, and Timothy F. Winters, 177-92. Paris: De Boccard, 2010.",
  "Skov, G.E. \"The Priestess of Demeter and Kore and Her Role in the Initiation of Women at the Festival of Haloa at Eleusis.\" Temenos 11 (1975): 136-47.",
  "Woloch, Michael. \"Four Leading Families in Roman Athens (A.D. 96-161).\" Zeitschrift für Alte Geschichte 18, no. 4 (1969): 503-10.",
  "Kapetanopoulos, Elias. \"Κλαύδιος Δεμόστρατος και Αὐρήλιος Εὐκαρπίδης.\" Archaiologike Ephemeris Chron (1974): 3-4.",
  "Kapetanopoulos, Elias. \"Flavius Hierophantes Paianieus and Lucius Verus.\" Revue des études grecques 83 (1970): 63-9.",
  "Geagan, Daniel. “A Family of Marathon and Social Mobility in Athens of the First Century B.C.” Phoenix 46, no. 1 (1992): 29-44.",
  "Kapetanopoulos, Elias. \"Leonides VII of Melite and his Family.\" Bulletin de correspondance hellénique 92 (1968): 493-518.",
  "Kapetanopoulos, Elias. \"Publius Aelius Sospis.\" Mnemosyne 22 (1969): 80-2.",
  "Avotins, Ivars. \"Prosopographical and Chronological Notes on some Greek Sophists of the Empire.\" Studies in Classical Antiquity 4 (1971): 67-80.",
  "Smith, Rowland B.E., \"A Lost Historian of Alexander 'Descended from Alexander', and Read by Julian? Praxagoras of Athens Reviewed in the Light of Attic Epigraphy.\" Zeitschrift für Alte Geschichte 56, no. 3 (2007): 356-380.",
  "Ameling, Walter. Herodes Atticus. 2 Vols. Subsidia Epigraphica 11. Hildesheim: Georg Olms, 1983.",
  "Dittenberger, W. \"Die Familie des Herodes Atticus.\" Hermes 13 (1878): 67-89.",
  "Foucart, P. \"La famille d'Hérode Atticus.\" Revue de philologie, de littérature et d'histoire anciennes 25 (1901): 89-91.",
  "Graindor, Paul. Un milliardaire antique. Hérode Atticus et sa famille. Cairo: Imprimerie Nationale, 1930.",
  "Grelle, F. \"L'epigrafe in onore di Erode Attico conservata a Stoccolma.\" in ΕΠΙΓΡΑΦΑΙ: miscellanea epigrafica in onore di Lidio Gasperini I, Edited by Gianfranco Paci, 455-9. Rome: Tipigraf, 2000.",
  "Humphreys, S. C. “Family Tombs and Tomb Cult in Ancient Athens: Tradition or Traditionalism?” The Journal of Hellenic Studies 100 (January 1, 1980): 96–126.",
  "Kennell, Nigel M. \"Herodes Atticus and the Rhetoric of Tyranny.\" Classical Philology 92, no. 4 (1997): 346-362.",
  "Perry, Ellen. \"Iconography and the Dynamics of Patronage: Sarcophagus from the Family of Herodes Atticus.\" Hesperia 70, no. 4 (2001): 461-492.",
  "Papalas, A.J. \"Herodes Atticus: An Essay on Education in the Antonine Age.\" History of Education Quarterly 21, no. 2 (1981): 171-88.",
  "Rife, Joseph. \"The Burial of Herodes Atticus: Elite Identity, Urban Society, and Public Memory in Roman Greece.\" Journal of Hellenic Studies 128 (2008): 92-127.",
  "Rutledge, Harry C. \"Herodes the Great: Citizen of the World.\" The Classical Journal 56, no. 3 (1960): 97-109.",
  "Spawforth, A.J.S. \"Sparta and the Family of Herodes Atticus.\" The Annual of the British School at Athens 75 (1980): 203-220.",
  "Swain, Simon. \"Promotion of Hadrian of Tyre and the Death of Herodes Atticus.\" Classical Philology 85, no. 3 (1990): 214-6.",
  "Tobin, Jennifer. Herodes Attikos and the City of Athens: Patronage and Conflict under the Antonines. Archaia Hellas 4. Amsterdam: J.C. Gieben, 1997.",
  "Bowes, Kim. Private Worship, Public Values, and Religious Change in Late Antiquity. Cambridge: Cambridge University Press, 2008.",
  "Eliot, C.W.J. \"A Bronze Counterpoise of Athena.\" Hesperia 45, no. 2 (1976): 163-70.",
  "Kapetanopoulos, Elias. \"The strategia in Athens after A.D. 250.\" Hellenica 42 (1991-2): 279-90.",
  "Kapetanopoulos, Elias. \"Remarks on Athens of about 270.\" Ἀρχαιολογικὰ Ἀνάλεκτα ἐξ Ἀθηνῶν 16 (1983): 51-7.",
  "Kaldellis, Anthony. “Julian, the Hierophant of Eleusis, and the Abolition of Constantius’ Tyranny.” The Classical Quarterly 55, no. 2 (December 1, 2005): 652–655.",
  "Frantz, Alison. The Middle Ages in the Athenian Agora. Princeton, NJ: American School of Classical Studies at Athens, 1961.",
  "Shear, T. Leslie Jr. \"Athens: From City-State to Provincial Town.\" Hesperia 50, no. 4 (1981): 356-77.",
  "Sironen, Erkki. \"An Honorary Epigram for Empress Eudocia in the Athenian Agora.\" Hesperia 59, no. 2 (1990): 371-4.",
  "Watts, Edward. City and School in Late Antique Athens and Alexandria. Berkeley: University of California Press, 2008."
];
